-- Job-Search Orchestrator — Postgres schema
-- Ported 2026-07-18 from live jobs.db DDL (not storage.SCHEMA, which drifted).
-- Policy lives in tracking.py: TRANSITIONS / REQUIRES_NOTE are the single
-- authority on legality (see its module docstring). This file carries
-- integrity: types, NOT NULL, FK, UNIQUE.
--
-- ONE narrow exception: jobs.status carries a generated domain CHECK, added
-- by storage.init_db() from tracking.status_domain_sql() -- NOT hardcoded
-- here, or it would become the second drifting list. It constrains which
-- values may exist, never which transitions are legal. Reason: post-cutover,
-- raw SQL writes status directly (including the migrator's --wipe
-- re-snapshot), bypassing _apply_transition, so a typo like 'drafcted' would
-- land silently. A loud CheckViolation at write time beats a quiet bad value
-- found three sessions later.
--
-- Tables and indexes are created idempotently: init_db runs this file on
-- every collect as an ensure-schema.

CREATE TABLE IF NOT EXISTS jobs (
    id                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- collection (Module 1)
    source            text NOT NULL,
    external_id       text NOT NULL,
    url               text,
    title             text,
    company           text,
    category          text,
    job_type          text,
    location          text,
    salary            text,
    description       text,
    publication_date  text,         -- source-provided, heterogeneous; kept raw
    fetched_at        timestamptz,  -- system-stamped; normalized to UTC in migration
    content_hash      text,
    -- scoring (Module 3)
    prefilter_pass    integer,
    ladder_match      text,
    relevance_score   integer,
    score_reason      text,
    -- tracking (Module 4)
    status            text NOT NULL DEFAULT 'new',
    status_updated_at timestamptz,
    notes             text,         -- WITHHELD (see db/roles.sql)
    cover_letter      text,         -- WITHHELD
    UNIQUE (source, external_id)
);

CREATE TABLE IF NOT EXISTS job_events (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id      integer NOT NULL REFERENCES jobs(id) ON DELETE RESTRICT,
    from_status text,
    to_status   text NOT NULL,
    at          timestamptz NOT NULL,
    note        text                -- WITHHELD
);

CREATE INDEX IF NOT EXISTS idx_events_job_at ON job_events (job_id, at);
