-- Job-Search Orchestrator — Postgres schema
-- Ported 2026-07-18 from live jobs.db DDL (not storage.SCHEMA, which drifted).
-- Deliberately NO status/transition CHECKs: policy lives in tracking.py
-- (TRANSITIONS / REQUIRES_NOTE are the single authority — see its module
-- docstring). This file carries integrity only: types, NOT NULL, FK, UNIQUE.

CREATE TABLE jobs (
    id                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- collection (Module 1)
    source            text NOT NULL,
    external_id       text NOT NULL,
    url               text,
    title             text,
    company           text,
    category          text,
    job_type          text,
    location          text,
    salary            text,
    description       text,
    publication_date  text,         -- source-provided, heterogeneous; kept raw
    fetched_at        timestamptz,  -- system-stamped; normalized to UTC in migration
    content_hash      text,
    -- scoring (Module 3)
    prefilter_pass    integer,
    ladder_match      text,
    relevance_score   integer,
    score_reason      text,
    -- tracking (Module 4)
    status            text NOT NULL DEFAULT 'new',
    status_updated_at timestamptz,
    notes             text,         -- WITHHELD (see db/roles.sql)
    cover_letter      text,         -- WITHHELD
    UNIQUE (source, external_id)
);

CREATE TABLE job_events (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id      integer NOT NULL REFERENCES jobs(id) ON DELETE RESTRICT,
    from_status text,
    to_status   text NOT NULL,
    at          timestamptz NOT NULL,
    note        text                -- WITHHELD
);

CREATE INDEX idx_events_job_at ON job_events (job_id, at);
